from enum import StrEnum


class WebhookSubscriptionEventsItem(StrEnum):
    ISSUECOMMENT_CREATED = "issue:comment_created"
    ISSUECREATED = "issue:created"
    ISSUEUPDATED = "issue:updated"
    PIPELINESPAN_CREATED = "pipeline:span_created"
    PROJECTUPDATED = "project:updated"
    PULLREQUESTAPPROVED = "pullrequest:approved"
    PULLREQUESTCHANGES_REQUEST_CREATED = "pullrequest:changes_request_created"
    PULLREQUESTCHANGES_REQUEST_REMOVED = "pullrequest:changes_request_removed"
    PULLREQUESTCOMMENT_CREATED = "pullrequest:comment_created"
    PULLREQUESTCOMMENT_DELETED = "pullrequest:comment_deleted"
    PULLREQUESTCOMMENT_REOPENED = "pullrequest:comment_reopened"
    PULLREQUESTCOMMENT_RESOLVED = "pullrequest:comment_resolved"
    PULLREQUESTCOMMENT_UPDATED = "pullrequest:comment_updated"
    PULLREQUESTCREATED = "pullrequest:created"
    PULLREQUESTFULFILLED = "pullrequest:fulfilled"
    PULLREQUESTPUSH = "pullrequest:push"
    PULLREQUESTREJECTED = "pullrequest:rejected"
    PULLREQUESTUNAPPROVED = "pullrequest:unapproved"
    PULLREQUESTUPDATED = "pullrequest:updated"
    REPOCOMMIT_COMMENT_CREATED = "repo:commit_comment_created"
    REPOCOMMIT_STATUS_CREATED = "repo:commit_status_created"
    REPOCOMMIT_STATUS_UPDATED = "repo:commit_status_updated"
    REPOCREATED = "repo:created"
    REPODELETED = "repo:deleted"
    REPOFORK = "repo:fork"
    REPOIMPORTED = "repo:imported"
    REPOPUSH = "repo:push"
    REPOTRANSFER = "repo:transfer"
    REPOUPDATED = "repo:updated"
