"""SDK-level exceptions for the Bitbucket Cloud SDK.

Hand-written; distinct from the autogenerated ``bb.cloud.errors`` module which
only contains :exc:`~bb.cloud.errors.UnexpectedStatus`.
"""

from __future__ import annotations

from bb.shared._errors import AuthenticationError as _Base

_HINT = (
    "Use APITokenAuth, OAuthTokenAuth, OAuthClientCredsAuth, or JWTAuth "
    "to build a BBClient with an accepted auth method."
)


class AuthenticationError(_Base):
    """Raised when a :class:`~bb.cloud.sdk._client.BBClient`'s auth method is
    not accepted by a Bitbucket Cloud API endpoint.

    All 336 Bitbucket Cloud REST API endpoints accept the same three schemes
    (as confirmed by querying ``bb_cloud_fixed.openapi.json`` via
    ``context/endpoint_security_index.md``): ``oauth2``, ``basic``,
    ``api_key``.  The SDK additionally supports ``jwt`` for Bitbucket Connect
    apps.

    The auth method is inferred from
    :attr:`~bb.cloud.client.AuthenticatedClient.prefix` and must map to one
    of the :class:`~bb.cloud.sdk._auth_validation.AuthMethod` members.

    Attributes:
        allowed: :class:`frozenset` of
            :class:`~bb.cloud.sdk._auth_validation.AuthMethod` values that
            the endpoint accepts.
        actual:  String describing the auth method inferred from the client
            (e.g. ``"oauth2"`` or ``"unknown (prefix='Digest')"``)

    Example::

        from bb.cloud.sdk._errors import AuthenticationError
        from bb.cloud.sdk._auth_validation import AuthMethod

        try:
            repo = await repos.get(client, workspace="ws", repo_slug="r")
        except AuthenticationError as exc:
            print(f"Need one of {exc.allowed!r}, got {exc.actual!r}")
    """

    def __init__(self, *, allowed: frozenset, actual: str) -> None:
        super().__init__(allowed=allowed, actual=actual, hint=_HINT)
