from enum import Enum


class RestPullRequestActivityAction(str, Enum):
    APPROVED = "APPROVED"
    AUTO_MERGE_CANCELLED = "AUTO_MERGE_CANCELLED"
    AUTO_MERGE_REQUESTED = "AUTO_MERGE_REQUESTED"
    COMMENTED = "COMMENTED"
    DECLINED = "DECLINED"
    DELETED = "DELETED"
    MERGED = "MERGED"
    MERGE_QUEUE_ADDED = "MERGE_QUEUE_ADDED"
    MERGE_QUEUE_EJECTED = "MERGE_QUEUE_EJECTED"
    OPENED = "OPENED"
    REOPENED = "REOPENED"
    RESCOPED = "RESCOPED"
    REVIEWED = "REVIEWED"
    REVIEW_COMMENTED = "REVIEW_COMMENTED"
    REVIEW_DISCARDED = "REVIEW_DISCARDED"
    REVIEW_FINISHED = "REVIEW_FINISHED"
    UNAPPROVED = "UNAPPROVED"
    UPDATED = "UPDATED"

    def __str__(self) -> str:
        return str(self.value)
