"""SDK-level exceptions for the Bitbucket Data Center SDK.

Hand-written; distinct from the autogenerated ``bb.datacenter.errors`` module
which only contains :exc:`~bb.datacenter.errors.UnexpectedStatus`.
"""

from __future__ import annotations

from bb.shared._errors import AuthenticationError as _Base

_HINT = "Use PersonalAccessTokenAuth or BasicAuth to build a BBDCClient with an accepted auth method."


class AuthenticationError(_Base):
    """Raised when a :class:`~bb.datacenter.sdk._client.BBDCClient`'s auth
    method is rejected by a Bitbucket Data Center API endpoint.

    Bitbucket Data Center REST API endpoints accept two authentication schemes:
    HTTP Basic Auth (username/password) and HTTP Bearer tokens (Personal Access
    Tokens).

    Attributes:
        allowed: :class:`frozenset` of
            :class:`~bb.datacenter.sdk._auth_validation.AuthMethod` values that
            the endpoint accepts.
        actual:  String describing the auth method inferred from the client
            (e.g. ``"bearer"`` or ``"unknown (prefix='Digest')"``)

    Example::

        from bb.datacenter.sdk._errors import AuthenticationError

        try:
            repo = await repos.get(client, project_key="PRJ", repo_slug="myrepo")
        except AuthenticationError as exc:
            print(f"Need one of {exc.allowed!r}, got {exc.actual!r}")
    """

    def __init__(self, *, allowed: frozenset, actual: str) -> None:
        super().__init__(allowed=allowed, actual=actual, hint=_HINT)
