from http import HTTPStatus
from typing import Any
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.get_import_job_messages_response_200 import GetImportJobMessagesResponse200
from ...models.get_import_job_messages_response_401 import GetImportJobMessagesResponse401
from ...models.get_import_job_messages_response_404 import GetImportJobMessagesResponse404
from ...types import UNSET, Response, Unset


def _get_kwargs(
    job_id: str,
    *,
    severity: str | Unset = UNSET,
    subject: str | Unset = UNSET,
    start: float | Unset = UNSET,
    limit: float | Unset = UNSET,
) -> dict[str, Any]:

    params: dict[str, Any] = {}

    params["severity"] = severity

    params["subject"] = subject

    params["start"] = start

    params["limit"] = limit

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/api/latest/migration/imports/{job_id}/messages".format(
            job_id=quote(str(job_id), safe=""),
        ),
        "params": params,
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> GetImportJobMessagesResponse200 | GetImportJobMessagesResponse401 | GetImportJobMessagesResponse404 | None:
    if response.status_code == 200:
        response_200 = GetImportJobMessagesResponse200.from_dict(response.json())

        return response_200

    if response.status_code == 401:
        response_401 = GetImportJobMessagesResponse401.from_dict(response.json())

        return response_401

    if response.status_code == 404:
        response_404 = GetImportJobMessagesResponse404.from_dict(response.json())

        return response_404

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[GetImportJobMessagesResponse200 | GetImportJobMessagesResponse401 | GetImportJobMessagesResponse404]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    job_id: str,
    *,
    client: AuthenticatedClient | Client,
    severity: str | Unset = UNSET,
    subject: str | Unset = UNSET,
    start: float | Unset = UNSET,
    limit: float | Unset = UNSET,
) -> Response[GetImportJobMessagesResponse200 | GetImportJobMessagesResponse401 | GetImportJobMessagesResponse404]:
    """Get import job messages

     Gets the messages generated by the job.

    Without any filter, all messages will be returned, but the response can optionally be filtered for
    the following severities. The severity parameter can be repeated to include multiple severities in
    one response.

    - INFO
    - WARN
    - ERROR

    The authenticated user must have **ADMIN** permission or higher to call this resource.

    Args:
        job_id (str):
        severity (str | Unset):
        subject (str | Unset):
        start (float | Unset):
        limit (float | Unset):  Example: 25.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[GetImportJobMessagesResponse200 | GetImportJobMessagesResponse401 | GetImportJobMessagesResponse404]
    """

    kwargs = _get_kwargs(
        job_id=job_id,
        severity=severity,
        subject=subject,
        start=start,
        limit=limit,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    job_id: str,
    *,
    client: AuthenticatedClient | Client,
    severity: str | Unset = UNSET,
    subject: str | Unset = UNSET,
    start: float | Unset = UNSET,
    limit: float | Unset = UNSET,
) -> GetImportJobMessagesResponse200 | GetImportJobMessagesResponse401 | GetImportJobMessagesResponse404 | None:
    """Get import job messages

     Gets the messages generated by the job.

    Without any filter, all messages will be returned, but the response can optionally be filtered for
    the following severities. The severity parameter can be repeated to include multiple severities in
    one response.

    - INFO
    - WARN
    - ERROR

    The authenticated user must have **ADMIN** permission or higher to call this resource.

    Args:
        job_id (str):
        severity (str | Unset):
        subject (str | Unset):
        start (float | Unset):
        limit (float | Unset):  Example: 25.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        GetImportJobMessagesResponse200 | GetImportJobMessagesResponse401 | GetImportJobMessagesResponse404
    """

    return sync_detailed(
        job_id=job_id,
        client=client,
        severity=severity,
        subject=subject,
        start=start,
        limit=limit,
    ).parsed


async def asyncio_detailed(
    job_id: str,
    *,
    client: AuthenticatedClient | Client,
    severity: str | Unset = UNSET,
    subject: str | Unset = UNSET,
    start: float | Unset = UNSET,
    limit: float | Unset = UNSET,
) -> Response[GetImportJobMessagesResponse200 | GetImportJobMessagesResponse401 | GetImportJobMessagesResponse404]:
    """Get import job messages

     Gets the messages generated by the job.

    Without any filter, all messages will be returned, but the response can optionally be filtered for
    the following severities. The severity parameter can be repeated to include multiple severities in
    one response.

    - INFO
    - WARN
    - ERROR

    The authenticated user must have **ADMIN** permission or higher to call this resource.

    Args:
        job_id (str):
        severity (str | Unset):
        subject (str | Unset):
        start (float | Unset):
        limit (float | Unset):  Example: 25.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[GetImportJobMessagesResponse200 | GetImportJobMessagesResponse401 | GetImportJobMessagesResponse404]
    """

    kwargs = _get_kwargs(
        job_id=job_id,
        severity=severity,
        subject=subject,
        start=start,
        limit=limit,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    job_id: str,
    *,
    client: AuthenticatedClient | Client,
    severity: str | Unset = UNSET,
    subject: str | Unset = UNSET,
    start: float | Unset = UNSET,
    limit: float | Unset = UNSET,
) -> GetImportJobMessagesResponse200 | GetImportJobMessagesResponse401 | GetImportJobMessagesResponse404 | None:
    """Get import job messages

     Gets the messages generated by the job.

    Without any filter, all messages will be returned, but the response can optionally be filtered for
    the following severities. The severity parameter can be repeated to include multiple severities in
    one response.

    - INFO
    - WARN
    - ERROR

    The authenticated user must have **ADMIN** permission or higher to call this resource.

    Args:
        job_id (str):
        severity (str | Unset):
        subject (str | Unset):
        start (float | Unset):
        limit (float | Unset):  Example: 25.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        GetImportJobMessagesResponse200 | GetImportJobMessagesResponse401 | GetImportJobMessagesResponse404
    """

    return (
        await asyncio_detailed(
            job_id=job_id,
            client=client,
            severity=severity,
            subject=subject,
            start=start,
            limit=limit,
        )
    ).parsed
